compatibility_date = "2024-11-30"
main = "src/index.ts"
name = "gdrive-webdav"

node_compat = true

# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true
head_sampling_rate = 1
